backend:
  name: git
  repo: longtoothban/LongToothSite # Replace with your GitHub repository
  branch: develop # Default branch name for your repo 
  token: "${LONGTOOTH_GITHUB_TOKEN}"

media_folder: "assets/images" # Folder for uploaded images
public_folder: "/assets/images"

collections:
  - name: "gigs"
    label: "Gigs"
    folder: "content/gigs"
    create: true
    fields:
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "location", label: "Location", widget: "string" }
      - { name: "details", label: "Details", widget: "text" }
